
name: Deploy Logic App


on:
  workflow_dispatch:

jobs:
  validate-and-deploy:
   runs-on: ubuntu-latest
   env:
     ENV_RESOURCEGROUP: RSG-DEV
     ENV_RESOURCEGROUPLOCATION: westeurope

   steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    

    - name: Validate ARM template
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./ARMTemplates/azure-logicapp-demo.deploy.json --parameters ./ARMTemplates/azure-logicapp-demo.deploy.parameters.json
    
    - name: Deploy Logic App
      run: |
       echo "::set-env name=logicappurl::$(az deployment group create -g RSG-DEV --template-file ./ARMTemplates/azure-logicapp-demo.deploy.json --parameters ./ARMTemplates/azure-logicapp-demo.deploy.parameters.json --query 'properties.outputs.logicAppUrl.value' -o tsv)"
      shell: bash   
      
    - name: Logout
      run: az logout
