name: Deploy Workbook


on: push

jobs:
  validate-and-deploy:
   runs-on: ubuntu-latest
   continue-on-error: true
   env:
     ENV_RESOURCEGROUP: RSG-DEV
     ENV_RESOURCEGROUPLOCATION: westeurope

   steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    

    - name: Validate ARM template
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./ARMTemplates/detect-persistance.json --parameters ./ARMTemplates/detect-persistance.parameters.json

    - name: Deploy Workbook
      run: az deployment group create -g RSG-DEV --template-file ./ARMTemplates/detect-persistance.json --parameters ./ARMTemplates/detect-persistance.parameters.json
      shell: bash
      
    - name: Logout
      run: az logout
