name: Create a Logic App

# Controls when the action will run. 

on:
    push:
      branches:
        - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
    validate-and-deploy:
     runs-on: ubuntu-latest
     env:
       ENV_RESOURCEGROUP: RSG-DEV
       ENV_RESOURCEGROUPLOCATION: westeurope
  
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@master

    #Use the azure provided action to log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
    # Create the resource group
    - name: Create Resource Group
      run: az group create -n ${{env.ENV_RESOURCEGROUP}} -l ${{env.ENV_RESOURCEGROUPLOCATION}}

    #Validate the  ARM template
    - name: Validate ARM template
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./ARMTemplates/azure-logicapp-demo.deploy.json --parameters ./ARMTemplates/azure-logicapp-demo.deploy.parameters.json
    
    #Deploy the ARM Template
    - name: Deploy Logic App
      run: |
       echo "::set-env name=logicappurl::$(az deployment group create -g az-logicapp-githubactions-demo-rg --template-file ./ARMTemplates/azure-logicapp-demo.deploy.json --parameters ./ARMTemplates/azure-logicapp-demo.deploy.parameters.json --query 'properties.outputs.logicAppUrl.value' -o tsv)"
      shell: bash   
      
    # Log Out From Azure 
    - name: Logout
      run: az logout